version: "3"

services:
  ecofunding_site:
    image: nome/imagem:latest
    expose:
      - 80
    restart: always
    container_name: solarium-site
    environment:
      PORT: 80
      HTTP_PORT: 80
      VIRTUAL_HOST: ecofunding.com.br
      LETSENCRYPT_HOST: ecofunding.com.br
      LETSENCRYPT_EMAIL: contato@ecofunding.com.br
      PRODUCTION_MODE: PRODUCTION
    networks:
      service_network:


networks:
  service_network:
    external:
      name: nome_da_rede
